language: python
python:
    - "2.7"

branches:
    except:
        - master

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq pandoc

install: "pip install -r requirements.txt --use-mirrors"

before_script:
    - "git submodule update --init --recursive"

script:
    - "make publish"

after_success:
    - make travis

env:
    global:
        secure: Egrt9UkxDfqUjI6vrK27E4i3I1v+r+X23f0VBhBbE9InmVW1OV3SgUqbyFT3oVCIRbA+cVh7D/CqNgs26ajWqpwJjwF74z3uAb0PYySwVKAhJiL4q921dADujADXjApHrtCWPJ/i0JF5aNpzkAtOzhQa2aSdvFrCV+rMSn9yyq8=
