language: python
python:
    - "2.7"

branches:
    except:
        - master

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq pandoc

install: "pip install -r requirements.txt --use-mirrors"

before_script:
    - "git submodule update --init --recursive"

script:
    - "make publish"

after_success:
    - git fetch origin master
    - make travis

env:
    global:
        secure: "H0AbrLaBNL9HheADd5+okPCG2ttl855YwOImyJSmMoiVRTAiEbMiaOL/Fu7ym+ymObDLOld12f72o4viImqgt/DHIRNM2/wdDS/fouvSpnXZOj8ZNUMwhIUBZnloS2MAFN3SpGp49fgGtiABj/z1Ze/7X5HhlSuUL6QD0CMzCbk="
