language: python
python:
    - "2.7"

branches:
    except:
        - master

before_script:
    - "git submodule update --init --recursive"

install: "pip install -r requirements.txt --use-mirrors"

script:
    - "make publish"
